---
    name: Deploy FastAPI App to EC2
    
    on:
      push:
        branches:
          - main
      pull_request:
        types: [closed]  # Trigger when a PR is merged into main
    
    jobs:
      deploy:
        runs-on: ubuntu-latest
        steps:
          # Checkout code from GitHub repository
          - name: Checkout repository
            uses: actions/checkout@v2
    
          # Set up SSH to connect to EC2 instance
          - name: Set up SSH
            uses: webfactory/ssh-agent@v0.5.3
            with:
              ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
    
          # Deploy FastAPI app to EC2
          - name: Deploy FastAPI app to EC2
            run: |
              ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
                cd /home/ubuntu/fastapi-book-project
                git pull origin main
                docker build -t fastapi-app .
                docker stop fastapi-container || true
                docker rm fastapi-container || true
                docker run -d --name fastapi-container -p 8000:8000 fastapi-app
                sudo systemctl restart nginx
              EOF
    